#! env zsh

source ~/.dotfiles/source/.shell/summarize

read line
echo $line > /tmp/document

[ -e /tmp/watson_qf ] && rm -fr /tmp/watson_qf

closest_classifier.sortdist /tmp/document | head -n10 | while read line
do
    key=$(echo $line | cut -d '.' -f1)
    file=$(cat $learning_dir/map/$key | cut -d':' -f1)
    linenr=$(cat $learning_dir/map/$key | cut -d':' -f2)
    content=$(cat $file | tail -n+$linenr | head -n5 | paste -d' ' -s)
    echo $file:$linenr:$content >> /tmp/watson_qf
done

line=$(cat /tmp/watson_qf | head -n1)
last_file=$(echo $line | cut -d':' -f1)
last_linenr=$(echo $line | cut -d':' -f2)
  #content=$(echo $line | awk '{FS=":"}{$1=""; $2=""; print}')
    content=$(echo $line | sed 's/^[^:]*:[^:]*://g')

echo $last_file:$last_linenr:$content

cat /tmp/watson_qf | while read line
do
    file=$(echo $line | cut -d':' -f1)
    linenr=$(echo $line | cut -d':' -f2)
    #content=$(echo $line | awk '{FS=":"}{$1=""; $2=""; print}')
    content=$(echo $line | sed 's/^[^:]*:[^:]*://g')

    if [ "$file" != "$last_file" ]
    then
        echo $file:$linenr:$content
        last_file=$file
        last_line=$linenr
    fi

    if [ "$file" = "$last_file" ] && [ $(($linenr - $last_linenr)) -gt 5 ]
    then
        echo $file:$linenr:$content
        last_file=$file
        last_linenr=$linenr
    fi
done

