sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker login -u="$HEROKUUSER" -p="$HEROKUPASS" $HEROKUREPO

install:
  - docker build -t jgontrum/spacyapi:base_v2 .
  - docker build -t jgontrum/spacyapi:en_v2 -f docker/en/Dockerfile .
  - docker build -t jgontrum/spacyapi:de_v2 -f docker/de/Dockerfile .
  - docker build -t jgontrum/spacyapi:es_v2 -f docker/es/Dockerfile .
  - docker build -t jgontrum/spacyapi:fr_v2 -f docker/fr/Dockerfile .
  - docker build -t jgontrum/spacyapi:nl_v2 -f docker/nl/Dockerfile .
  - docker build -t jgontrum/spacyapi:pt_v2 -f docker/pt/Dockerfile .
  - docker build -t jgontrum/spacyapi:it_v2 -f docker/it/Dockerfile .
  - docker build -t jgontrum/spacyapi:all_v2 -f docker/all/Dockerfile .

after_success:
  - docker push jgontrum/spacyapi:base_v2
  - docker push jgontrum/spacyapi:en_v2
  - docker push jgontrum/spacyapi:de_v2
  - docker push jgontrum/spacyapi:es_v2
  - docker push jgontrum/spacyapi:fr_v2
  - docker push jgontrum/spacyapi:pt_v2
  - docker push jgontrum/spacyapi:it_v2
  - docker push jgontrum/spacyapi:nl_v2
  - docker push jgontrum/spacyapi:all_v2
  - docker tag jgontrum/spacyapi:en_v2 registry.heroku.com/spacy-en/web
  - docker push registry.heroku.com/spacy-en/web
  - docker tag jgontrum/spacyapi:de_v2 registry.heroku.com/spacy-de/web
  - docker push registry.heroku.com/spacy-de/web
