FROM ubuntu:14.04

RUN apt-get update && apt-get install -y wget gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libfreetype6 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk2.0-0 libnspr4 libnss3 libpango1.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libcurl3 xdg-utils

RUN wget http://staruml.io/download/release/v2.8.1/StarUML-v2.8.1-64-bit.deb
RUN dpkg -i StarUML-v2.8.1-64-bit.deb

ENTRYPOINT staruml
